config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :medicos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  #resources :agendas { 
    get '/agendas', to: 'agendas#index'
    get '/agendas/new', to: 'agendas#new', as: 'new_agenda'
    post '/agendas', to: 'agendas#create'
    get '/agendas/:id', to: 'agendas#show'
    get '/agendas/:id/edit', to: 'agendas#edit', as: :edit_agenda
    #aqui em edit ocorreu o mesmo erro de undefind local... method, foi colocado o as: :edit_agenda
    put '/agendas/:id', to: 'agendas#update'
    delete '/agendas/:id', to: 'agendas#destroy', as: :agenda
  # }

end

app/models/agenda.rb
class Agenda < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medico.rb
class Medico < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: %i[ show edit update destroy ]

  # GET /agendas or /agendas.json
  def index
    @agendas = Agenda.all
  end

  # GET /agendas/1 or /agendas/1.json
  def show
    @parametros = params
    #? O params é um obj fornecido pelo Rails que contém todos os parâmetros passados para solicitação HTTP.
    #? Ele pode incluir informações como os parâmetros de consulta, de rota e dos dados do formulário submetido. 
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas or /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to agenda_url(@agenda), notice: "Agenda was successfully created." }
        format.json { render :show, status: :created, location: @agenda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1 or /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to agenda_url(@agenda), notice: "Agenda was successfully updated." }
        format.json { render :show, status: :ok, location: @agenda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1 or /agendas/1.json
  def destroy
    @agenda.destroy!

    respond_to do |format|
      format.html { redirect_to agendas_url, notice: "Agenda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agenda_params
      params.require(:agenda).permit(:paciente, :medico)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: %i[ show edit update destroy ]

  # GET /medicos or /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1 or /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos or /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully created." }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1 or /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully updated." }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1 or /medicos/1.json
  def destroy
    @medico.destroy!

    respond_to do |format|
      format.html { redirect_to medicos_url, notice: "Medico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medico_params
      params.require(:medico).permit(:name, :experience)
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy!

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:nome__cliente, :data_pedido, :status_pedido, :forma_pagamento, :valor_total)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @var_controller_index = "Oi, eu sou uma variável declarada no controller 
    -> welcome_controller.rb <- e instanciada com @var_controller_index no welcome.html.erb nas views
    para que eu possa aparecer aqui para você no navegador."
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agendas/_agenda.html.erb
<div id="<%= dom_id agenda %>">
  <p>
    <strong>Paciente:</strong>
    <%= agenda.paciente %>
  </p>

  <p>
    <strong>Medico:</strong>
    <%= agenda.medico %>
  </p>

</div>

app/views/agendas/_form.html.erb
<%= form_for @agenda, :html => { :class => "form-horizontal agenda" } do |f| %>

  <% if @agenda.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @agenda.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :paciente, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :paciente, :class => 'form-control' %>
    </div>
    <%=f.error_span(:paciente) %>
  </div>
  <div class="form-group">
    <%= f.label :medico, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :medico, :class => 'form-control' %>
    </div>
    <%=f.error_span(:medico) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                agendas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/agendas/edit.html.erb
<%- model_class = Agenda -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agendas/index.html.erb
<%- model_class = Agenda -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:paciente) %></th>
      <th><%= model_class.human_attribute_name(:medico) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= link_to agenda.id, agenda_path(agenda) %></td>
        <td><%= agenda.paciente %></td>
        <td><%= agenda.medico %></td>
        <td><%=l agenda.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      agenda_path(agenda), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_agenda_path(agenda), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      agenda_path(agenda),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_agenda_path,
            :class => 'btn btn-primary' %>

<!-- botão com tradução 
<%= link_to t('.back', :default => t("helpers.links.Página Inicial")),
             root_path,
             :class => 'btn btn-info' %> -->

<%= link_to 'Página Inicial', root_path, :class => 'btn btn-info' %>

app/views/agendas/new.html.erb
<%- model_class = Agenda -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agendas/show.html.erb
<%- model_class = Agenda -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:paciente) %>:</strong></dt>
  <dd><%= @agenda.paciente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medico) %>:</strong></dt>
  <dd><%= @agenda.medico %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              agendas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_agenda_path(@agenda), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              agenda_path(@agenda),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Projeto" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Projeto</a> <!-- root -->
        <!-- <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div> -->
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Navegação Rápida</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Tópicos</li>
              <li><%= link_to "Consultar Agendas", agendas_path %></li>
              <li><%= link_to "Consultar Médicos", "/medicos"  %></li>
              <li><%= link_to "Tela de Buscas Pedidos", "/path3"  %></li>
              <li><%= link_to "Link4", "/path3"  %></li>
              <li><%= link_to "Link5", "/path3"  %></li>
              <li><%= link_to "Link6", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2024</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/medicos/_form.html.erb
<%= form_with(model: medico) do |form| %>
  <% if medico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
        <% medico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :experience, style: "display: block" %>
    <%= form.text_field :experience %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/_medico.html.erb
<div id="<%= dom_id medico %>">
  <p>
    <strong>Name:</strong>
    <%= medico.name %>
  </p>

  <p>
    <strong>Experience:</strong>
    <%= medico.experience %>
  </p>

</div>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Show this medico", @medico %> |
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medicos</h1>

<div id="medicos">
  <% @medicos.each do |medico| %>
    <%= render medico %>
    <p>
      <%= link_to "Show this medico", medico %>
    </p>
  <% end %>
</div>

<%= link_to "New medico", new_medico_path %>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medico %>

<div>
  <%= link_to "Edit this medico", edit_medico_path(@medico) %> |
  <%= link_to "Back to medicos", medicos_path %>

  <%= button_to "Destroy this medico", @medico, method: :delete %>
</div>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome__cliente, style: "display: block" %>
    <%= form.text_field :nome__cliente %>
  </div>

  <div>
    <%= form.label :data_pedido, style: "display: block" %>
    <%= form.date_field :data_pedido %>
  </div>

  <div>
    <%= form.label :status_pedido, style: "display: block" %>
    <%= form.number_field :status_pedido %>
  </div>

  <div>
    <%= form.label :forma_pagamento, style: "display: block" %>
    <%= form.number_field :forma_pagamento %>
  </div>

  <div>
    <%= form.label :valor_total, style: "display: block" %>
    <%= form.text_field :valor_total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Nome  cliente:</strong>
    <%= pedido.nome__cliente %>
  </p>

  <p>
    <strong>Data pedido:</strong>
    <%= pedido.data_pedido %>
  </p>

  <p>
    <strong>Status pedido:</strong>
    <%= pedido.status_pedido %>
  </p>

  <p>
    <strong>Forma pagamento:</strong>
    <%= pedido.forma_pagamento %>
  </p>

  <p>
    <strong>Valor total:</strong>
    <%= pedido.valor_total %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Página index do welcome</h1>

<h4>Estou em app > views > welcome > index.html.erb</h4></br>
<h4>
    Após o <b>controlador</b> ter processado a solicitação e <b>obtido os dados
    necessários do modelo</b>, ele renderiza uma visão para ser enviada de volta
    ao navegador. Ou seja, aqui recebe as <b>informações do controlador</b> e gera a interface
    do usuário.
</h4></br>

<h4>
    <%= @var_controller_index %>
</h4>

<p>A frase acima está instanciada aqui no index da pasta welcome 
    é só colocar: @var_controller_index que aparece o que está dentro do método INDEX do controller. 
    Dentro desse método, está declarada essa variável no qual faz referência a essa frase acima.</p>
</br>

<h2>AGENDAS</h2>
<!-- 
#! Existem duas formas de como colocar um link para uma página, 
#! essa forma abaixo não é tão recomendada pois tem que escrever manualmente a rota e 
#! em caso de alteração, terá que alterar manualmente cada uma. 
<a href="/agendas/new">Cadastro de Agenda</a> 

#? O recomendável é que seja escrita as rotas com o seu path 
-->
<%= link_to 'Cadastro de Agenda', agendas_path, :class => 'btn btn-info' %>